// Generated by gencpp from file project6/OddEvenCheck.msg
// DO NOT EDIT!


#ifndef PROJECT6_MESSAGE_ODDEVENCHECK_H
#define PROJECT6_MESSAGE_ODDEVENCHECK_H

#include <ros/service_traits.h>


#include <project6/OddEvenCheckRequest.h>
#include <project6/OddEvenCheckResponse.h>


namespace project6
{

struct OddEvenCheck
{

typedef OddEvenCheckRequest Request;
typedef OddEvenCheckResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct OddEvenCheck
} // namespace project6


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::project6::OddEvenCheck > {
  static const char* value()
  {
    return "4ff0b0ab1ed04611e3a2b4090af9ee4f";
  }

  static const char* value(const ::project6::OddEvenCheck&) { return value(); }
};

template<>
struct DataType< ::project6::OddEvenCheck > {
  static const char* value()
  {
    return "project6/OddEvenCheck";
  }

  static const char* value(const ::project6::OddEvenCheck&) { return value(); }
};


// service_traits::MD5Sum< ::project6::OddEvenCheckRequest> should match
// service_traits::MD5Sum< ::project6::OddEvenCheck >
template<>
struct MD5Sum< ::project6::OddEvenCheckRequest>
{
  static const char* value()
  {
    return MD5Sum< ::project6::OddEvenCheck >::value();
  }
  static const char* value(const ::project6::OddEvenCheckRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::project6::OddEvenCheckRequest> should match
// service_traits::DataType< ::project6::OddEvenCheck >
template<>
struct DataType< ::project6::OddEvenCheckRequest>
{
  static const char* value()
  {
    return DataType< ::project6::OddEvenCheck >::value();
  }
  static const char* value(const ::project6::OddEvenCheckRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::project6::OddEvenCheckResponse> should match
// service_traits::MD5Sum< ::project6::OddEvenCheck >
template<>
struct MD5Sum< ::project6::OddEvenCheckResponse>
{
  static const char* value()
  {
    return MD5Sum< ::project6::OddEvenCheck >::value();
  }
  static const char* value(const ::project6::OddEvenCheckResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::project6::OddEvenCheckResponse> should match
// service_traits::DataType< ::project6::OddEvenCheck >
template<>
struct DataType< ::project6::OddEvenCheckResponse>
{
  static const char* value()
  {
    return DataType< ::project6::OddEvenCheck >::value();
  }
  static const char* value(const ::project6::OddEvenCheckResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PROJECT6_MESSAGE_ODDEVENCHECK_H
