// Generated by gencpp from file project6/TurnCamera.msg
// DO NOT EDIT!


#ifndef PROJECT6_MESSAGE_TURNCAMERA_H
#define PROJECT6_MESSAGE_TURNCAMERA_H

#include <ros/service_traits.h>


#include <project6/TurnCameraRequest.h>
#include <project6/TurnCameraResponse.h>


namespace project6
{

struct TurnCamera
{

typedef TurnCameraRequest Request;
typedef TurnCameraResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TurnCamera
} // namespace project6


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::project6::TurnCamera > {
  static const char* value()
  {
    return "48e9c72001527a85ebcc47fcec8f9237";
  }

  static const char* value(const ::project6::TurnCamera&) { return value(); }
};

template<>
struct DataType< ::project6::TurnCamera > {
  static const char* value()
  {
    return "project6/TurnCamera";
  }

  static const char* value(const ::project6::TurnCamera&) { return value(); }
};


// service_traits::MD5Sum< ::project6::TurnCameraRequest> should match
// service_traits::MD5Sum< ::project6::TurnCamera >
template<>
struct MD5Sum< ::project6::TurnCameraRequest>
{
  static const char* value()
  {
    return MD5Sum< ::project6::TurnCamera >::value();
  }
  static const char* value(const ::project6::TurnCameraRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::project6::TurnCameraRequest> should match
// service_traits::DataType< ::project6::TurnCamera >
template<>
struct DataType< ::project6::TurnCameraRequest>
{
  static const char* value()
  {
    return DataType< ::project6::TurnCamera >::value();
  }
  static const char* value(const ::project6::TurnCameraRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::project6::TurnCameraResponse> should match
// service_traits::MD5Sum< ::project6::TurnCamera >
template<>
struct MD5Sum< ::project6::TurnCameraResponse>
{
  static const char* value()
  {
    return MD5Sum< ::project6::TurnCamera >::value();
  }
  static const char* value(const ::project6::TurnCameraResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::project6::TurnCameraResponse> should match
// service_traits::DataType< ::project6::TurnCamera >
template<>
struct DataType< ::project6::TurnCameraResponse>
{
  static const char* value()
  {
    return DataType< ::project6::TurnCamera >::value();
  }
  static const char* value(const ::project6::TurnCameraResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PROJECT6_MESSAGE_TURNCAMERA_H
